### ISSUE TITLE
No property to display all client commands

### ISSUE THREAD

**Issue by Loliticos** [discord-akairo/discord-akairo#109]
Currently, there's no property to display all client commands.

**Comment by zfbx** [comment]
there is `this.handler.categories` which you can iterate over and get the commands through there if that's what you mean?

**Comment by ItsPapaia** [comment]
`this.handler.categories` is the categories, each category has commands in it.
Additionally, `this.handler.modules` is a `Collection<string, Command>`, so I really don't get what you're saying.

**Comment by Loliticos** [comment]
What I'm saying is that it's currently possible to display all categories commands, but what if you want to list all of them? You'll need to loop all categories and show the commands. There could be a simple way by adding a Client property and making it array.

**Comment by ItsPapaia** [comment]
> You'll need to loop all categories and show the commands.

You don't have to iterate over the categories, because as I mentioned,
> `this.handler.modules` is a `Collection<string, Command>`

And there you have your commands (`this.handler` inside commands is your CommandHandler).

> There could be a simple way by adding a Client property and making it array.

Would not happen.
Command handlers, listener handlers, and inhibitor handlers are all `AkairoHandler`s, which have a `modules` property, containing their modules (commands etc.), if you want a client property, add a getter, the "issue" you mentioned, is not an issue.
